server:
  port: 8080
spring:
  thymeleaf:
    prefix:
      classpath: /templates/
      suffix: .html
    mode: HTML5
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/database_demo1?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8&useSSL=false
    username: root
    password: 123xq
    driver-class-name: com.mysql.cj.jdbc.Driver

